### ISSUE TITLE
Custom name for items

### ISSUE THREAD

**Issue by gregoryduckworth** [TypiCMS/NestableCollection#10]
Rather than returning a list of items, allowing a custom name to be chosen would make it more readable and also able to work out the box with other packages.

**Comment by sdebacker** [comment]
Hello @gregoryduckworth, what do you mean by a custom name ?

**Comment by gregoryduckworth** [comment]
So instead of being 'items', the name could be changed to 'children', this would make it easier to work with packages such as the d3 graph library

**Comment by sdebacker** [comment]
Good idea, are you ok to make a pull request with a publishable config file, so we can choose a different name ?

**Comment by sdebacker** [comment]
You can now change the name by a method : $collection->childrenName('children')->nest();
