### ISSUE TITLE
What is the best way to load every children of current model?

### ISSUE THREAD

**Issue by darron1217** [TypiCMS/NestableCollection#17]
If the model is also a child of root, how can I get the children of current model? (including children of children too)

**Comment by sdebacker** [comment]
The best way is using CTEs with PostgreSQL or waiting for MySQL 8: https://stackoverflow.com/questions/31641504/adjacency-list-model-vs-nested-set-model-for-mysql-hierarchical-data

Otherwise, for small trees, you can add a children method in you model, like this:
```php
public function children()
{
    return $this->hasMany(self::class, 'parent_id');
}
```
and then in a loop:
```php
$model->load('children');
```

**Comment by darron1217** [comment]
@sdebacker Thanks for the feedback :)

**Comment by NormanEdance** [comment]
Can you guys post implementation, cuz I'm stuck too
