### ISSUE TITLE
Nest method changed

### ISSUE THREAD

**Issue by nWidart** [TypiCMS/NestableCollection#2]
Was there a breaking change introduced recently ?

The `->nest()` is returning 0 items again. (items are ordered by parent_id, with no changed on this end.)

When running `dd($this->items);` after line 60 (`$this->items = array_values(array_except($this->items, $keysToDelete));`) I get an empty array.

**Comment by sdebacker** [comment]
I don't think so… strange.

**Comment by sdebacker** [comment]
Mmh I pushed wrong thing. I correct it now

**Comment by sdebacker** [comment]
I just pushed v1.0.2, does it work better ?

**Comment by nWidart** [comment]
Hm it's weird. On one installation I can see the menu tree. On a clean install, not. 
They both have the same DB schema though... :/

**Comment by nWidart** [comment]
For anyone else having the same issue: 
The solution is to have `null` in the root element `parent_id` column.
