### ISSUE TITLE
Why i should get the weird error.

### ISSUE THREAD

**Issue by shankhadevpadam** [TypiCMS/NestableCollection#22]
```
$categories = Category::orderByRaw('-name ASC')
        ->get()
        ->nest()
        ->listsFlattened('name');
dd($categories);
```
```
proc_open(): fork failed - Cannot allocate memory
```

**Comment by sdebacker** [comment]
Hello,
Difficult to say, but it seems to be not related to this package.

**Comment by shankhadevpadam** [comment]
> Hello,
> Difficult to say, but it seems to be not related to TypiCMS.

**Comment by shankhadevpadam** [comment]
Not worked in laravel 6. You can try.

**Comment by sdebacker** [comment]
What is orderByRaw('-name ASC') ? It looks strange to me.

**Comment by shankhadevpadam** [comment]
```
Category::orderBy('parent_id')->get()->nest()->setIndent('> ')->listsFlattened();
```
This code is worked in below laravel version 6, but in 6 it's not working above error occur.

**Comment by sdebacker** [comment]
I checked and could not reproduce this bug. Perhaps your tree is really big, in this case a memory problem can occur.
