### ISSUE TITLE
Private variables in NestableCollection

### ISSUE THREAD

**Issue by bjhijmans** [TypiCMS/NestableCollection#26]
I have extended NestableCollection in my application, but I can't access the internal variables in NestableCollection from my extended class because they're private. Could you please make them protected instead so I can use them?

**Comment by sdebacker** [comment]
Hello, sorry for my late reply. I'm open for a pull request.

**Comment by bjhijmans** [comment]
I added two pull requests. 

#29 only sets the variables to protected to allow extension. 

#30 also includes the addition I was making when I first posted this, which adds a function to set the parent relation of each item, so you can call `$item->parent` without querying the database.
Usage: `$query->get()->nest()->setParents()`
